### ISSUE TITLE
Make magicpen-media an optional dependency

### ISSUE THREAD

**Issue by gustavnikolaj** [unexpectedjs/unexpected-messy#3]
After updating plugins on my PR for [express-interceptor]() the owner noticed that magicpen-media was installed as a dependency as well, and asked why, as it didn't seem to be used. https://github.com/axiomzen/express-interceptor/pull/24

I had some trouble asking it, but @sunesimonsen pointed me in the right direction.

`unexpected-express`'s use of `unexpected-messy` would rarely have a use for `magicpen-media` if any. Couldn't we change it so that magicpen-media was an optional dependency that you could add if you need it?

Or is this just a part of the bigger "how can we properly handle dependencies"-situation?

**Comment by papandreou** [comment]
Since unexpected-messy uses `output.media`, it would lead to an "undefined is not a function" error if it's not installed, which would be hard to debug. Also, it would require unexpected-messy to try...catch the require.

I can see why it's annoying to end up with more direct dependencies than you bargained for, but I'd rather not take measures that go towards demodularizing code that should be in separate modules. Let's not do anything until we know the npm 3 story wrt. those `peerDependencies`.

**Comment by papandreou** [comment]
If anything, I want to move more output-related features into modules, eg. magicpen-stringdiff. We really need to find a way to prevent this from leaking out so much.

**Comment by gustavnikolaj** [comment]
I'm all for modulizing, and You're right- we should wait for npm@3 -
It's not the first time we reach that realization.

I think they have a beta or alpha release out already actually.

Den onsdag den 15. juli 2015 skrev Andreas Lind <notifications@github.com>:

**Comment by papandreou** [comment]
I believe this situation is fixed as of Unexpected 9.5.0 and the newest version of unexpected-express, unexpected-messy etc.

See: https://github.com/axiomzen/express-interceptor/pull/30
